# Application configuration
client:
    key: ${EPAM_DIAL_API_KEY}
    endpoint: https://ai-proxy.lab.epam.com
    deploymentModels:
        openAi: gpt-35-turbo-0125
        amazon: amazon.titan-tg1-large

prompt:
  openai:
    completion:
      maxTokens: 100
      temperature: 0.5
      topP: 0.3
      frequencyPenalty: 0.0
      presencePenalty: 0.0
